![logo itq](img/imgitq.jpeg)

## Tercer Módulo-Python, NumPy

![logo python](img/imgpython.jpeg)

*Mónica Guano*

# NumPy ndarray
- NumPy (__Num__ erical __Py__ thon) es la de facto librería estándar para análisis numérico en Python
- Estructura de datos multidimensional eficiente (escrita en C): ndarray
- Colección de funciones para álgebra lineal, estadística descriptiva
- Ayuda al procesamiento de datos (np.where)

In [4]:
#importar libreria
import numpy as np

## Performance Sample, NumPy vs Plain Python

In [5]:
my_list = list(range(10000000)) # Utilizando Listas Python
%time my_list = [x * 2 for x in my_list]

CPU times: total: 2.17 s
Wall time: 2.19 s


In [6]:
my_arr = np.arange(10000000)  # Utilizando NumPy Arrays
%time my_arr2 = my_arr * 2

CPU times: total: 46.9 ms
Wall time: 40.9 ms


## Formas de crear ndarrays

In [7]:
array = np.array([ [2,71,0,34], [2,171,-35,34] ]) # 2D
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [8]:
shopping_list = [ ['onions', 'carrots', 'celery'], ['apples', 'oranges', 'grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [9]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,10,2.1))    # array a partir de una secuencia(range) 1D

[100  10   1]
[2.  4.1 6.2 8.3]


In [10]:
# Generar arrays con valores fijos
print(np.zeros(2))       # 1D
print(np.ones((4,3)))    # matriz 2x2 o 4X3
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),2)) # matrix 5x2
print(np.eye(4))         # matrix identity (la diagonal tiene 1)

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Obtener información sobre ndarray

In [11]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray)

[ 2 71  0 34]


In [12]:
print(my_ndarray.argmax())    # índice del valor más alto
print(np.amax(my_ndarray))

print(my_ndarray.argmin())    # índice del valor más bajo
print(np.amin(my_ndarray))

print(my_ndarray.nonzero())   # retorna los índices de los elementos distintos a 0

1
71
2
0
(array([0, 1, 3]),)


In [13]:
my_ndarray = np.full((5, 4,2), 2) # matrix 5x2x2
print(my_ndarray)

print(my_ndarray.size)        # número de elementos
print(my_ndarray.shape)       # dimensiones
print(my_ndarray.ndim)        # número de dimensiones

[[[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]]
40
(5, 4, 2)
3


In [14]:
my_ndarray = np.array([2,71,0,34])

print(my_ndarray.size)        # número de elementos
print(my_ndarray.shape)       # dimensiones
print(my_ndarray.ndim)        # número de dimensiones

4
(4,)
1


#### Redimensionar los datos

In [20]:
my_ndarray = np.array([[0, 71, 21, 19, 213, 412, 111, 98]])  # matrix 1x8
print(my_ndarray)
print(my_ndarray.shape)
print(my_ndarray.ndim) # es de 2 dimensiones por los 2 corchetes

[[  0  71  21  19 213 412 111  98]]
(1, 8)
2


In [21]:
new_dims = my_ndarray.reshape(2, 4)  # cambiar las dimensiones a 2x4
print(new_dims)
print(new_dims.ndim)

[[  0  71  21  19]
 [213 412 111  98]]
2


In [22]:
new_dims = my_ndarray.reshape(4, 2)  # cambiar las dimensiones a 4x2
print(new_dims)
print(new_dims.ndim)

[[  0  71]
 [ 21  19]
 [213 412]
 [111  98]]
2


In [23]:
x = np.array([100, 10, 1]).reshape(3,1)
print(x.shape)
print(x)

(3, 1)
[[100]
 [ 10]
 [  1]]


In [25]:
# reducir a 1D
new_dims = np.arange(9).reshape(3,3)
print(new_dims)
print(new_dims.flatten()) # reduce la matriz a una sola dimensión

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [27]:
# reducir
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(new_dims.reshape(2,-1))    # el segundo valor se infiere del primero (Divide a la mitad los elementos)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


## Manipulación de ndarrays

In [30]:
# Cambiar ejes
new_dims = np.arange(16).reshape(8,2)
print(new_dims)
print(new_dims.swapaxes(0,1)) # Esta funcíón la cambia Python, cambio de filas por columnas

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]


In [31]:
# Flip
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(np.flip(new_dims, axis = None))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [33]:
# ordenar
array1 = np.array([10,2,9,17])
array1.sort()   # esta función permite ordenar los elementos
print(array1)

[ 2  9 10 17]


In [34]:
# Juntar dos arrays
a1 = [0,0,0,0,0,0]
a2 = [1,1,1,1,1,1]

print(np.hstack((a1,a2))) # una al lado de la otra
print(np.hstack((a1,a2)).shape)

print(np.vstack((a1,a2))) # una encima de la otra
print(np.vstack((a1,a2)).shape)

[0 0 0 0 0 0 1 1 1 1 1 1]
(12,)
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(2, 6)


In [35]:
array1 = np.array([[2, 4], [6, 8]]) 
array2 = np.array([[3, 5], [7, 9]])
  
print(np.concatenate((array1, array2), axis = 0))

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [36]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array, 2, axis = 0)) # divide array en 2 partes iguales
print(np.array_split(array, 3)) # divide array en 3 partes "iguales"

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [74]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array, [3], axis = 1)) # divide array, por la fila 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [75]:
split = np.array_split(array, [3], axis = 1)
print(split[0][3][0])

12


In [76]:
array = np.arange(64).reshape(8,8)
print(array)
print(np.array_split(array, [1, 3], axis = 0))  # divide array por la fila 1 y 3

print(np.array_split(array, [1, 3], axis = 1))  # divide array por la columna 1 y 3
# axis = n_dimensions - 1

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

# Índices y slicing
- De manera análoga a índices y slicing para listas

In [77]:
array = np.arange(10, 16)
print(array)
print(array[-1])    # acceso unidimensional
print(array[:-1])  # slice

[10 11 12 13 14 15]
15
[10 11 12 13 14]


In [78]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)
print(array[2, 2]) # fila, columna # la fila y columna se cuentan desde cero
print(array[3][2]) # fila, columna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
14


In [140]:
# multidimensional
array = np.arange(36).reshape(2,3,6)
print(array)
print(array[0,2,4])     # matiz 0
print(array[1][2][4])   # matriz 1

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
16
34


#### NumPy es row major

In [144]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3)  # by default, row major.....# 2 filas, 3 columnas
print(row_major)

[[1 2 3]
 [4 5 6]]


In [145]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3,order='C')  # by default, row major
print(row_major)

col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2,3,order='F')  # col major
print(col_major)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


#### Slice

In [147]:
# se puede hacer slice por fila o columna
array = np.arange(81).reshape(9,9)
print(array)      # Toma de la fila índice 1 hasta la 3 (sin incluir la 3). Es decir, selecciona las filas 1 y 2
print(array[1:3, 2::2])   # El primer '2' es el inicio (columna índice 2). El segundo ':2' es el SALTO (step), 
                          # Es decir, toma la columna 2, se salta una, toma la 4, se salta una, toma la 6.

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[11 13 15 17]
 [20 22 24 26]]


In [148]:
# se puede hacer slice por fila o columna
array = np.arange(9).reshape(3,3)  #matriz de 3x3
print(array)
print(array[0,:]) # el signo : equivale a todas las columnas

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


#### Diferencias entre índices y slicing en listas y ndarrays:
- ¡Retornan una referencia, no una copia!

In [151]:
# uso de slice en listas, retorna copia
lista = [0,1,2,3,4,5,6,7,8,9]
my_copy = lista[0:2]  # devuelve una copia; el cero es incluyente y el 2 excluyente, solo va el 0 y 1
print(my_copy)
my_copy[0] = 222    # Como es una copia, este cambio vive en un espacio de memoria distinto.
print(lista)   #Imprime la lista original, en la cual el 1er elemento sigue siendo 0
print(my_copy) #Imprime la copia mofidicada

[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [54]:
# slicing retorna una referencia en ndarrays
array = np.arange(10)
my_copy = array[2:5]  # devuelve una referencia; 2 es incluyente y el 5 excluyente; impirme los # 2,3,4
print(array)
print(my_copy)
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [58]:
# copiar ndarrays
array = np.arange(10)
my_copy = array[2:5].copy()  # hay que hacer la copia explicitamente
my_copy[0] = 222             # en mi copia en la posicipon 0 inclui el 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


- Permite asignar valores a un corte

In [81]:
array = np.arange(10)
print(array)

print(array[0:3])     #el 0 incluyente y el 3 excluyente; impirme los # 0,1,2
 
array[0:3] = -1       # reemplazo los # 0,1,2 por -1
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[-1 -1 -1  3  4  5  6  7  8  9]


- Slicing condicionales (mask)

In [89]:
# slicing condicional
array = np.arange(-3,4)    # La función arange(inicio, fin) genera un rango de números, el -3 es incluyente y el 4 excluyente; imprime los # -3, -2, -1,  0,  1,  2,  3
print(array)

mask = array %2 == 0   #(mask es filtro), en lugar de usar un bucle for, NumPy aplica la operación a cada elemento, Calcula el residuo de la división entre 2 (% 2). Compara si es igual a cero, es decir, si el número es par. El resultado es un nuevo array de valores booleanos (True o False) con la misma forma que el original.
print(mask)
print(array[mask])  # Al pasarle la mask (los booleanos) al array original dentro de los corchetes, NumPy solo devuelve los valores donde la posición es True. 
                    # Es una forma extremadamente eficiente de filtrar datos.

print(array[array %2 == 0])

array[mask] = 0    # Aquí le estás diciendo: "En todas las posiciones donde el número era par, reemplázalo por un 0".
print(array)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-2  0  2]
[-3  0 -1  0  1  0  3]


In [90]:
array = np.arange(-3,4)
print(array)

array[array < 0] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[0 0 0 0 1 2 3]


In [139]:
# slicing condicional
array = np.arange(-3,4)
print(array)

mask = array % 2 == 0
print(mask)

array_par = array[mask]  # devuelve una copia
print(array_par)

array_par[0] = -10
print(array)
print(array_par)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-10   0   2]


- Acceso a múltiples valores con listados de índices

In [156]:
array = np.arange(0,16).reshape(4,4)
print(array)
print(array[[1,2]])  #selecting rows
print(array[:,[1,2]])   #selecting columns

# cross product of indexes
print(array[[1,2],:][:,[1,2]])

print(array[np.ix_([1,2],[1,2])])  # built in ix_

ar = array[[2,3,1]] # slice, copia
print(ar)
ar[0] = 999
print(ar)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 4  5  6  7]]
[[999 999 999 999]
 [ 12  13  14  15]
 [  4   5   6   7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### hasta aquí completar qué hace cada celda

# Funciones matemáticas
- Aplicar operaciones entre escalares y arrays o entre arrays

In [62]:
# listas y escalares
lista = [0,1,2,3]
lista *= 3   # se repite la lista 3 veces
print(lista)

lista += [1] # se añade el 1 al final de la lista
print(lista)

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [64]:
# ndarray hace las operaciones sobre los elementos
array = np.ones(4, dtype = np.int8) # es un tipo dato de arreglo de datos, diferente al punto anterior
print(array)
array *= 2
print(array)

array += 10
print(array)

print(array.dtype)  # check data type of array

[1 1 1 1]
[2 2 2 2]
[12 12 12 12]
int8


In [65]:
# operaciones entre arrays es como operaciones entre matrices
array_1 = np.ones(4) * 2
array_2 = np.arange(4) + 1

print(array_1)
print(array_2)

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_2 / array_1)

[2. 2. 2. 2.]
[1 2 3 4]
[3. 4. 5. 6.]
[ 1.  0. -1. -2.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]


## Broadcasting

Si las arrays no tienen las mismas dimensiones, se hace broadcast del pequeño al grande -> [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

## Operadores unarios y binarios

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

In [157]:
# ejemplos de operadores
array = np.arange(5)
print(array)
np.sqrt(array) # obtener la raiz cuadrada de cada elemento de la lista

[0 1 2 3 4]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [158]:
# ejemplos de operadores
array1 = np.arange(4)
array2 = np.array([0,-1,2,-3])

print(array1)
print(array2)

print(np.greater(array1,array2))   #comparación de condicionales
print(np.less(array2, array1))

[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False  True False  True]


# Estadística descriptiva
- Importante saber la naturaleza de los datos
- Valores máximos, mínimos, distribución, etc.

| Función | Descripción |
|:---------|:-----|
| *sum(arr)* | Suma de todos los elementos de *arr* |
| *mean(arr)* | Media aritmética de los elementos de *arr* |
| *std(arr)* | Desviación estándar de los elementos de *arr* |
| *cumsum(arr)* | Devuelve array con la suma acumulada de cada elementos con todos los anteriores |
| *cumprod(arr)* | Devuelve array con el producto acumulado de cada elementos con todos los anteriores |
| *min(arr), max(arr)* | Mínimo y máximo de *arr* |
| *any(arr)* | En array de tipo *bool*, retorna *True* si algún elemento es *True* |
| *all(arr)* | En array de tipo *bool*, retorna *True* si todos los elementos son *True* (o <>0 en valores numéricos) |
| *unique(arr)* | Devuelve un array con valores únicos |
| *in1d(arr1, arr2)* | Devuelve un array con bool indicando si cada elemento de *arr1* está en *arr2* |
| *union1d(arr1, arr2)* | Devuelve la unión de ambos arrays |
| *intersect1d(arr1, arr2)* | Devuelve la intersección de ambos arrays |

In [159]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())

[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [160]:
# any vs all
array1 = np.arange(-8,2).reshape(2,5)
print(array1)
print(array1.any()) # any para saber si hay elementos True o valores <> 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores <> 0

[[-8 -7 -6 -5 -4]
 [-3 -2 -1  0  1]]
True
False


In [161]:
# todas las funciones aceptan parametro 'axis' 
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1.all(axis=0))
print(array1.all(axis=1))
print(array1.all())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]
False


# Álgebra lineal
- numpy.linalg contiene funciones para álgebra lineal
- dot product, multiplicación de matrices, cálculo del determinante, factorizaciones...


| Función | Descripción |
|:---------|:-----|
| *dot(mat1, mat2)* | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas |
| *matmul(mat1, mat2)* | Devuelve el producto entre dos matrices |
| *trace(mat1, mat2)* | Suma de las diagonales de ambas matrices |
| *det(mat)* | Devuelve el determinante de la matriz |
| *eig(mat)* | Computa los autovalores y autovectores de la matriz cuadrada *mat* |
| *inv(mat)* | Devuelve la inversa de la matriz |
| *qr(mat)* | Computa la factorización QR de *mat* |
| *solve(A, b)* | Resuelve el sistema lineal de ecuaciones *Ax = b* para *b*, cuando *A* es una matriz cuadrada |
| *transpose(mat)* | Devuelve la transpuesta de la matrix |

In [165]:
A = np.arange(12).reshape(4,3)
B = np.arange(6).reshape(3,2)

print(A)
print(B)

#regla para multiplicación de matrices: el # de columans de la 1er matriz debe concidir con el # de filas de la 2da matriz

print(np.matmul(A, B)) #producto de 2 matrices
print(np.dot(A, B))    #producto escalar entre 2 matrices
print(A @ B)           #producto de matrices (las 3 formas dan el mismo resultado)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [166]:
import numpy.linalg as lg
import math

# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x - 3y -z = 2
# 2x -y +12z = 32
# Ax = b --> resolver para x

a = np.array([ [3,2,5], [1,-3,-1], [2,-1,12] ])  #sacar los factores numéricos
b = np.array([12,2,32])

print(a)
print(b)
x,y,z = lg.solve(a,b)
print(f'x={x} y={y} z={z}')

print(math.isclose(3*x + 2*y +5*z, 12))
print(math.isclose(x - 3*y - z, 2))
print(math.isclose(2*x -y + 12*z, 32))

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122807 y=-1.2280701754385965 z=2.43859649122807
True
True
True


In [73]:
#matriz identidad
I = np.identity(4)
print(I)

A = np.arange(16).reshape(4,4)  #arange: crea una lista de números del 0 al 15; reshape:crea la matriz de 4x4
print(A)

print(np.matmul(A,I))   #la matriz identidad (I) actúa como el número 1 en la multiplicación escalar.

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


### Enlace: [Python_NumPy](https://github.com/moniloag-png/Introduccionpythonnocturno/blob/main/PAO25_25_06_Python_NumPy.ipynb)

# Filtrado de datos
- Filtrar y modificar datos numéricos con np.where
- Retorna A o B en función de una condición en una array

In [167]:
prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49])
mask = prices < 1
print(prices[prices < 1]) #slicing condicional

# mask con los elementos menores de 1
mask = np.where(prices < 1, True, False)
print(mask)
print(prices[mask])

prices[mask] = 1.0
print(prices)

print(np.where(prices < 1, 1.0, prices))

[0.99 0.49]
[ True False False False  True]
[0.99 0.49]
[ 1.   14.49 19.99 20.99  1.  ]
[ 1.   14.49 19.99 20.99  1.  ]


In [96]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0)
print(clean_data)

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [100]:
# limpiar NaN (sustitución)
data = [10, 12, -143, np.nan, 1, -3] # np.nan --> NotANumber, elemento especial. se reemplaza por 0
print (data)
data_clean = np.where(np.isnan(data), 0, data)
print(data_clean)

print(id(data))
print(id(data_clean))

[10, 12, -143, nan, 1, -3]
[  10.   12. -143.    0.    1.   -3.]
2129253555008
2129262461840


In [103]:
# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)    #generamos la matriz 2x3
print(bank_transfers_values)
credits = np.where(bank_transfers_values > 0) # array de índices para los que la condición es True

print(credits)
print(bank_transfers_values[credits]) # es igual que bank_transfers_values[bank_transfers_values > 0]
print(bank_transfers_values[bank_transfers_values > 0])

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))
[ 0.99 19.99 20.99 12.1 ]
[ 0.99 19.99 20.99 12.1 ]


In [104]:
# valor de array dependiendo del valor en array referencia
rewards_default = np.arange(6)
print(rewards_default)

rewards_upgrade = np.arange(6) * 10
print(rewards_upgrade)

daily_points = np.array([0, 0, 1, 6, 0, 2])
print(daily_points)

final_rewards = np.where(daily_points > 1, rewards_upgrade, rewards_default)
print(final_rewards)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[ 0  1  2 30  4 50]


# Números aleatorios
- Python módulo random

In [108]:
import random

print(random.random()) # número entre 0 y 1
print(random.randint(0,5)) # integral entre dos valores
print(random.uniform(0,5)) # real entre dos valores

0.49677879816335857
4
0.8583240014034138


In [112]:
# elegir un elemento al azar dentro de una colección
names = ['Pikachu','Eevee','Charmander']
random.choice(names)   # esta función elige un dato aleatorio de una lista

'Charmander'

## NumPy.random
- Generar fácilmente listas con valores aleatorios

In [116]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # integral entre dos valores 
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las dimensiones)

0.40794454214655507
2
[[4 3 3 2]
 [1 4 3 0]]


In [118]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4,2))

[[-0.45692814  0.61763317]
 [-0.90923907  0.06777765]
 [ 0.51333092  0.47625269]
 [-0.40751679 -0.78850024]]


In [120]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias esperadas, retornar 'size' valores

0
7.847205700910953
[[3 0]
 [1 3]]


## Random seed
- Números pseudo-aleatorios
- Ordenadores generan números a partir de ecuaciones
- Basadas en un número inicial (seed)
- Bueno para reproducibilidad de experimentos

In [121]:
i = 5
for _ in range(5):
    np.random.seed(i) # misma semilla
    print(np.random.rand())
    print(np.random.rand())

print()    
    
for i in range(6):
    np.random.seed(i) # diferentes semillas
    print(np.random.rand())
    print(np.random.rand())

0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764

0.5488135039273248
0.7151893663724195
0.417022004702574
0.7203244934421581
0.43599490214200376
0.025926231827891333
0.5507979025745755
0.7081478226181048
0.9670298390136767
0.5472322491757223
0.22199317108973948
0.8707323061773764


# Escritura y lectura de ndarrays a archivos 
- Para futuro acceso
- Compartir datos con otros
- Formato *.npy

In [125]:
# escribir a archivo
import os
ruta = os.path.join("res" ,"o_values_array.npy")

values = np.random.randint(9, size=(3,3))
np.save(ruta, values)
print(values)

[[2 7 0]
 [5 0 0]
 [4 4 3]]


In [126]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)

[[2 7 0]
 [5 0 0]
 [4 4 3]]


In [152]:
# escribir y cargar múltiples arrays
ruta = os.path.join("res" ,"o_array_group.npz")

values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3) # añade la extensión .npz   

In [130]:
# leer los archivos (retorna un diccionario con las arrays)
npzfile = np.load(ruta)

print(type(npzfile.files))
print(npzfile.files)

for key in npzfile.files: # array.files contiene el nombre de las arrays (arr_0, arr_1...)
     print(npzfile[key])

<class 'list'>
['arr_0', 'arr_1', 'arr_2']
[[0 6 0]
 [5 2 8]
 [6 8 0]]
[[0 0]
 [1 2]]
[[15 14  2  0]
 [ 7  7  6 11]
 [ 0  0  8 10]
 [12 14  5 14]]


### ¿Por qué molestarse con .npy?
- Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)
- ¿Para qué escribir los datos de nuevo?

In [153]:
import os
ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
# print(data_array)

ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)

In [134]:
%%timeit # magic function jupyter
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data,  dtype = np.int8).reshape(1000,1000)

454 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [136]:
%%timeit
data = np.load(ruta_npy)

1.3 ms ± 93.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [138]:
%%timeit # magic function jupyter
result = np.fromfile(ruta_csv, dtype=np.int8, sep=",")

1.14 s ± 33.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### velocidad + simplicidad vs memoria

## Ejercicios

- Ejercicios para practicar NumPy: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb


#### 1. Import the numpy package under the name

In [172]:
# 1. Importar el paquete numpy bajo el nombre np
# Esto carga la librería en la memoria de Python y le asigna el alias 'np'
# para que el código sea más breve y estandarizado.
import numpy as np

# Verificación (Opcional):
# Podemos imprimir la versión para confirmar que se importó correctamente.
print(f"NumPy importado exitosamente. Versión: {np.__version__}")

NumPy importado exitosamente. Versión: 2.4.0


#### 2. Imprime la version y configuracion del NumPy 

In [178]:
import numpy as np

# Imprime la versión y la configuración de forma directa
print("Versión:", np.__version__)
np.show_config()

# EXPLICACIÓN: Este código importa la librería NumPy y usa dos comandos esenciales: 
    #'__version__' para saber qué versión tienes instalada y 
    #'show_config()' para listar las dependencias internas del sistema.

Versión: 2.4.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas con

#### 3. Crea un vector nulo de tamaño 10

In [182]:
import numpy as np

# Creamos una fila de 10 ceros
vector = np.zeros(10)

print(vector)

# EXPLICACIÓN:
    #- np.zeros(10): Esta función le pide a NumPy que fabrique una lista (vector) con 10 espacios y que rellene cada uno con el número 0.
    #- Un 'vector nulo' en programación es simplemente una fila llena de ceros.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. "¿Cómo encontrar el tamaño de memoria de cualquier arreglo (array)?"

In [183]:
import numpy as np

# Creamos un arreglo de ejemplo
arreglo = np.zeros((10, 10))

# Calculamos el tamaño total en memoria
tamaño_total = arreglo.size * arreglo.itemsize

print(f"El arreglo ocupa {tamaño_total} bytes")

# EXPLICACIÓN: Para saber cuánto pesa el arreglo, multiplicamos dos cosas:
    # 1. arreglo.size: Cuántos elementos hay en total (ej. 100 números).
    # 2. arreglo.itemsize: Cuánto pesa cada número individualmente

El arreglo ocupa 800 bytes


#### 5. ¿Cómo obtener la documentación de la función add de NumPy desde la línea de comandos?

In [186]:
import numpy as np

# Muestra la ayuda y manual de la función sumar
np.info(np.add)

### EXPLICACIÓN: La función 'np.info()' es como un manual de instrucciones rápido. Al escribir 'np.add' adentro, Python te muestra para qué sirve, qué datos necesita y qué resultado te dará la función de suma.

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Crear un vector nulo de tamaño 10, pero que el quinto valor sea 1".

In [191]:
import numpy as np

# 1. Creamos una fila de 10 ceros
vector = np.zeros(10)

# 2. Cambiamos el quinto lugar (posición 4) por un 1
vector[4] = 1

print(vector)

# NOTA:
    #- np.zeros(10): Crea 10 espacios llenos de ceros.
    #- vector[4] = 1: En programación empezamos a contar desde 0. 
  # Por eso, la "quinta posición" es el número 4. Aquí le decimos que cambie ese cero por un 1.

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Crear un vector con valores en un rango de 10 a 49.

In [197]:
import numpy as np

# Creamos el vector que inicia en 10 y termina antes de 50
vector = np.arange(10, 50)

print(vector)

# EXPLICACIÓN:
    # * np.arange(10, 50): Esta función genera una lista de números.
    # * El primer número (10) es donde empieza.
    # * El segundo número (50) es el límite, pero NO se incluye. 
  # Por eso, el vector se detiene exactamente en el 49.

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Invertir un vector (el primer elemento se convierte en el último).

In [199]:
import numpy as np

# 1. Creamos un vector con números del 0 al 9
vector = np.arange(10)

# 2. Lo invertimos usando el comando [::-1]
vector_invertido = vector[::-1]

print(vector_invertido)

# EXPLICACIÓN:
# - np.arange(10): Crea una lista del 0 al 9.
# - [::-1]: Es un truco que le dice a Python: "recorre la lista completa, 
#   pero da pasos de -1 (hacia atrás)". Esto voltea el orden."

[9 8 7 6 5 4 3 2 1 0]


#### 9. Crear una matriz de 3x3 con valores que vayan del 0 al 8".

In [201]:
import numpy as np

# 1. Creamos una lista de números del 0 al 8
# 2. Reorganizamos esa lista en una forma de 3 filas y 3 columnas
matriz = np.arange(9).reshape(3, 3)

print(matriz)


# EXPLICACIÓN:
# - np.arange(9): Crea una fila con los números [0, 1, 2, 3, 4, 5, 6, 7, 8].
# - .reshape(3, 3): Toma esos 9 números y los acomoda en una cuadrícula 
#   de 3 filas y 3 columnas.

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Encontrar los índices de los elementos que no son cero en la lista [1, 2, 0, 0, 4, 0].

In [205]:
import numpy as np

# 1. Creamos el arreglo con los números
lista = np.array([1, 2, 0, 0, 4, 0])

# 2. Buscamos las posiciones de los números que NO son cero
indices = np.nonzero(lista)

print(indices)

# EXPLICACIÓN:
# - np.array([...]): Convierte la lista simple en un arreglo de NumPy.
# - np.nonzero(lista): Busca dentro de la lista y te dice en qué dirección o posición están los números distintos a cero.

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [210]:
import numpy as np

# Crea una matriz identidad de 4x4
matriz = np.identity(4)

print(matriz)

# EXPLICACIÓN:
# - np.identity(4): Crea una tabla cuadrada de 4 filas y 4 columnas.
# - Al igual que np.eye, coloca el número 1 en la diagonal (de esquina a esquina) y llena el resto con el número 0.

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Crear un arreglo de 3x3x3 con valores aleatorios.

In [212]:
import numpy as np

# Creamos un cubo de números (3 capas, 3 filas, 3 columnas)
cubo = np.random.random((3, 3, 3))

print(cubo)

# EXPLICACIÓN:
# - np.random.random: Genera números al azar entre 0 y 1.
# - (3, 3, 3): El primer 3 indica "capas" o "profundidad". Es como tener 3 tablas de 3x3 apiladas una sobre otra, formando un cubo.

[[[0.78191488 0.83021552 0.24107067]
  [0.85496366 0.14261648 0.759887  ]
  [0.93354342 0.71597823 0.12805138]]

 [[0.122318   0.60531038 0.98359658]
  [0.90447715 0.26103618 0.59673101]
  [0.3340151  0.44550347 0.6449255 ]]

 [[0.34167404 0.84414    0.62830878]
  [0.20018449 0.38096354 0.52351223]
  [0.67537613 0.28125893 0.7534345 ]]]


### Enlace: [Python_NumPy](https://github.com/moniloag-png/Introduccionpythonnocturno/blob/main/PAO25_25_06_Python_NumPy.ipynb)